server:
  port: 8080

email: dev@info.com

spring:
  profiles:
    active: dev
  application:
    name: Random Food Application (Dev)
  datasource:
    url: jdbc:mysql://food-db.chbqadkiacz2.eu-west-1.rds.amazonaws.com:3306/dbfood
    username: sysadmin
    password: 024680Aws
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
#    hibernate:
#      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        generate_statistics: true
        id:
          new_generator_mappings: true
logging:
  level:
    root: WARN
    com.randomfood.food: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
