server:
  port: 8082

email: prod@info.com

spring:
  profiles:
    active: prod
  application:
    name: Random Food Application (Prod)
  h2:
    console:
      enabled: true
#  datasource:
#    url: jdbc:mysql://localhost/prod
#    jndi-name: prod-jndi
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate.format_sql: true
#      hibernate.id.new_generator_mappings: true
#      hibernate.cache.use_second_level_cache: true
#      hibernate.cache.use_query_cache: false
#      hibernate.generate_statistics: true
#
logging:
  level:
    root: WARN
    com.randomfood.food: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
